/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Author struct {
	AuthorId string `json:"authorId"`
	// ORCID/DBLP IDs for this author, if known
	ExternalIds *interface{} `json:"externalIds,omitempty"`
	// URL on the Semantic Scholar website
	Url string `json:"url,omitempty"`
	Name string `json:"name,omitempty"`
	// List of names the author has used on publications over time, not intended to be displayed to users. WARNING: this list may be out of date or contain deadnames of authors who have changed their name. (see https://en.wikipedia.org/wiki/Deadnaming)
	Aliases *interface{} `json:"aliases,omitempty"`
	// Research institutions that author is affiliated with - sourced from authors who have set this information on their S2 author page.
	Affiliations *interface{} `json:"affiliations,omitempty"`
	// Author's own homepage
	Homepage string `json:"homepage,omitempty"`
	// Author's total publications count
	PaperCount string `json:"paperCount,omitempty"`
	// Author's total citations count
	CitationCount string `json:"citationCount,omitempty"`
	// https://www.semanticscholar.org/faq#h-index
	HIndex string `json:"hIndex,omitempty"`
}
