/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AllOfPaperSearchBatchDataItems struct {
	// A unique (string) identifier for this paper.<
	PaperId string `json:"paperId"`
	// A second unique (numeric) identifier for this paper.
	CorpusId string `json:"corpusId,omitempty"`
	// Other catalog IDs for this paper, if known. Supports ArXiv, MAG, ACL, PubMed, Medline, PubMedCentral, DBLP, DOI.
	ExternalIds *interface{} `json:"externalIds,omitempty"`
	// URL on the Semantic Scholar website
	Url string `json:"url,omitempty"`
	Title string `json:"title,omitempty"`
	// The paper's abstract. Note that due to legal reasons, this may be missing even if we display an abstract on the website.
	Abstract string `json:"abstract,omitempty"`
	// normalized venue name
	Venue string `json:"venue,omitempty"`
	// Details about the journal or conference in which this paper was published
	PublicationVenue string `json:"publicationVenue,omitempty"`
	// year of publication
	Year int32 `json:"year,omitempty"`
	// Total number of papers referenced by this paper
	ReferenceCount int32 `json:"referenceCount,omitempty"`
	// Total number of citations S2 has found for this paper
	CitationCount int32 `json:"citationCount,omitempty"`
	// https://www.semanticscholar.org/faq#influential-citations
	InfluentialCitationCount int32 `json:"influentialCitationCount,omitempty"`
	// https://www.openaccess.nl/en/what-is-open-access
	IsOpenAccess bool `json:"isOpenAccess,omitempty"`
	// A link to the paper if it is open access, and we have a direct link to the pdf. As well as the paper's status. More info on status here: https://en.wikipedia.org/wiki/Open_access#Colour_naming_system
	OpenAccessPdf string `json:"openAccessPdf,omitempty"`
	// A list of high-level academic categories from external sources.
	FieldsOfStudy *interface{} `json:"fieldsOfStudy,omitempty"`
	// This field returns a list of objects, where each has two keys: 'category' and 'source'. There are two sources: 'external' - same as 'fieldsOfStudy', 's2-fos-model' - an internally developed classifier, see https://www.semanticscholar.org/faq#how-does-semantic-scholar-determine-a-papers-field-of-study
	S2FieldsOfStudy *interface{} `json:"s2FieldsOfStudy,omitempty"`
	// The type of this publication
	PublicationTypes []string `json:"publicationTypes,omitempty"`
	// Year-month-day when this paper was published
	PublicationDate string `json:"publicationDate,omitempty"`
	// Journal name, volume, and pages
	Journal *interface{} `json:"journal,omitempty"`
	// Bibliographic citations for paper, currently supported styles: BibTeX
	CitationStyles *interface{} `json:"citationStyles,omitempty"`
	Authors []AuthorInfo `json:"authors,omitempty"`
}
