/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AllOfCitationBatchDataItems struct {
	// Snippets of text where the reference is mentioned
	Contexts *interface{} `json:"contexts,omitempty"`
	// https://www.semanticscholar.org/faq#citation-intent
	Intents *interface{} `json:"intents,omitempty"`
	// Similar to \"contexts\" but each context comes its associated intents. Each object returned in this list has two keys: 'context' - the text snippet, and 'intents' - associated intents for this context.
	ContextsWithIntent *interface{} `json:"contextsWithIntent,omitempty"`
	// https://www.semanticscholar.org/faq#influential-citations
	IsInfluential bool `json:"isInfluential,omitempty"`
	// Details about the citing paper
	CitingPaper *interface{} `json:"citingPaper"`
}
