/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PaperInfo struct {
	// A unique (string) identifier for this paper.<
	PaperId string `json:"paperId"`
	// A second unique (numeric) identifier for this paper.
	CorpusId string `json:"corpusId,omitempty"`
	// URL on the Semantic Scholar website
	Url string `json:"url,omitempty"`
	Title string `json:"title,omitempty"`
	// normalized venue name
	Venue string `json:"venue,omitempty"`
	// Details about the journal or conference in which this paper was published
	PublicationVenue string `json:"publicationVenue,omitempty"`
	// year of publication
	Year int32 `json:"year,omitempty"`
	Authors []AuthorInfo `json:"authors,omitempty"`
}
